version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - UVICORN_CMD=uvicorn apps.main:app --host 0.0.0.0 --port 8002 --reload
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge
